export interface InstallationService {
  id: string;
  bookingName: string;
  title: string;
  summary: string;
  includes: string[];
  duration: string;
  demoPrice: number;
  image: string;
}

export const INSTALLATION_SERVICES: InstallationService[] = [
  { id: '4x4-face-lifts', bookingName: '4x4 Face lifts', title: '4x4 Face Lifts', summary: 'Refresh the exterior character of your 4x4 with carefully selected front-end and styling upgrades.', includes: ['Vehicle-specific planning', 'Fitment and alignment', 'Final quality inspection'], duration: 'Time confirmed after inspection', demoPrice: 150000, image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=1200&q=85&fit=crop' },
  { id: 'ppf', bookingName: 'PPF', title: 'Paint Protection Film', summary: 'Help protect frequently exposed painted or interior surfaces from everyday scratches and wear.', includes: ['Surface preparation', 'Precision film application', 'Edge and finish inspection'], duration: 'Depends on coverage area', demoPrice: 85000, image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=1200&q=85&fit=crop' },
  { id: 'detailing', bookingName: 'DETAILING', title: 'Professional Detailing', summary: 'A thorough appearance-care service designed to restore a cleaner, fresher and more polished finish.', includes: ['Condition assessment', 'Interior or exterior treatment', 'Finishing inspection'], duration: 'Usually same day', demoPrice: 15000, image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=1200&q=85&fit=crop' },
  { id: 'wrapping', bookingName: 'WRAPPING', title: 'Vehicle Wrapping', summary: 'Transform or protect selected vehicle surfaces with professionally applied automotive wrap.', includes: ['Colour and coverage consultation', 'Surface preparation', 'Professional application'], duration: 'Depends on coverage area', demoPrice: 120000, image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200&q=85&fit=crop' },
  { id: 'anti-uv-tints', bookingName: 'Anti UV tints', title: 'Anti-UV Window Tints', summary: 'Reduce glare and ultraviolet exposure while giving the glass a clean, refined appearance.', includes: ['Tint selection', 'Glass preparation', 'Bubble-free application'], duration: 'Approximately 2–4 hours', demoPrice: 12000, image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&q=85&fit=crop' },
  { id: 'sports-kits', bookingName: 'Sports kits', title: 'Sports Kits', summary: 'Give your vehicle a coordinated, sportier exterior with professionally aligned styling components.', includes: ['Vehicle fitment check', 'Component alignment', 'Secure installation'], duration: 'Time confirmed after inspection', demoPrice: 65000, image: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=1200&q=85&fit=crop' },
  { id: 'sports-exhaust', bookingName: 'Sports Exhaust', title: 'Sports Exhaust', summary: 'Upgrade the rear styling and exhaust character with a solution selected for your vehicle.', includes: ['Compatibility inspection', 'Mounting and alignment', 'Final operation check'], duration: 'Depends on vehicle and setup', demoPrice: 25000, image: 'https://images.unsplash.com/photo-1611821064430-0d40291d0f0b?w=1200&q=85&fit=crop' },
  { id: 'seat-covers', bookingName: 'Seat Covers', title: 'Seat Covers', summary: 'Refresh cabin comfort and appearance with neatly fitted covers selected for your seating layout.', includes: ['Seat configuration check', 'Careful fitting', 'Finish inspection'], duration: 'Approximately 1–3 hours', demoPrice: 18000, image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=85&fit=crop' },
  { id: 'mats', bookingName: 'Mats', title: 'Car Mats', summary: 'Protect your vehicle floor with a cleanly fitted mat solution suited to your cabin.', includes: ['Fitment selection', 'Placement and adjustment', 'Pedal-clearance check'], duration: 'Approximately 30 minutes', demoPrice: 8000, image: 'https://images.unsplash.com/photo-1570733577524-3a047079e80d?w=1200&q=85&fit=crop' },
  { id: 'polishes', bookingName: 'Polishes', title: 'Paint Polishing', summary: 'Improve gloss and revive tired-looking paintwork with professional surface preparation and polishing.', includes: ['Paint condition check', 'Surface preparation', 'Polishing and final finish'], duration: 'Usually same day', demoPrice: 10000, image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=1200&q=85&fit=crop' },
  { id: 'sun-visors', bookingName: 'Sun visors', title: 'Sun Visors', summary: 'Add practical shade and a tidy exterior accent with correctly aligned visor installation.', includes: ['Fitment confirmation', 'Surface preparation', 'Secure alignment'], duration: 'Approximately 30–60 minutes', demoPrice: 5000, image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=85&fit=crop' },
  { id: 'air-press', bookingName: 'Air Press', title: 'Air Press Installation', summary: 'Reduce wind turbulence with vehicle-appropriate air press fitted neatly around the windows.', includes: ['Vehicle fitment check', 'Alignment and mounting', 'Window operation check'], duration: 'Approximately 30–60 minutes', demoPrice: 6000, image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=1200&q=85&fit=crop' },
  { id: 'fog-lamps', bookingName: 'Fog Lamps', title: 'Fog Lamp Installation', summary: 'Improve low-level road illumination and complete the front-end look with professional fitting.', includes: ['Compatibility check', 'Mounting and wiring', 'Beam and operation test'], duration: 'Approximately 1–2 hours', demoPrice: 12000, image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200&q=85&fit=crop' },
  { id: 'anti-heat-tints', bookingName: 'Anti-heat Tints', title: 'Heat-Reducing Tints', summary: 'Improve cabin comfort by reducing solar heat and glare through professionally applied film.', includes: ['Film consultation', 'Glass preparation', 'Professional application'], duration: 'Approximately 2–4 hours', demoPrice: 18000, image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?w=1200&q=85&fit=crop' },
];

export const INSTALLATION_SERVICE_NAMES = INSTALLATION_SERVICES.map(service => service.bookingName);
